name: Build and Push to Amazon ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPO_APP: webapp
  ECR_REPO_DB: mysql

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push WebApp image to ECR
        run: |
          docker build -t $ECR_REPO_APP -f Dockerfile .
          docker tag $ECR_REPO_APP:latest ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_APP}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_APP}:latest

      - name: Build and push MySQL image to ECR
        run: |
          docker build -t $ECR_REPO_DB -f Dockerfile_mysql .
          docker tag $ECR_REPO_DB:latest ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_DB}:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/${ECR_REPO_DB}:latest
